VERILOG_SOURCES += $(RTL_DIR)/axi_lite_slave.sv
VERILOG_SOURCES += $(RTL_DIR)/axi_lite_slave.sv
VERILOG_SOURCES += $(RTL_DIR)/svo_bram.sv
VERILOG_SOURCES += $(RTL_DIR)/svo_traversal.sv
VERILOG_SOURCES += $(RTL_DIR)/shading_pipeline.sv
VERILOG_SOURCES += $(RTL_DIR)/framebuffer.sv
VERILOG_SOURCES += $(RTL_DIR)/pixel_upscaler.sv
VERILOG_SOURCES += $(RTL_DIR)/hdmi_timing.sv
VERILOG_SOURCES += $(RTL_DIR)/top.sv
TOPLEVEL         = top
MODULE           = test_top
TOPLEVEL_LANG    = verilog

include ../Makefile.common
