VERILOG_SOURCES += $(RTL_DIR)/shared_qmul3.sv
VERILOG_SOURCES += $(RTL_DIR)/qmul_bank_tagged.sv
TOPLEVEL         = qmul_bank_tagged
MODULE           = test_qmul_bank_tagged
TOPLEVEL_LANG    = verilog

include ../Makefile.common
