VERILOG_SOURCES += $(RTL_DIR)/svo_bram.sv
VERILOG_SOURCES += $(RTL_DIR)/shared_qmul3.sv
VERILOG_SOURCES += $(RTL_DIR)/svo_traversal.sv
TOPLEVEL         = svo_traversal
TOPLEVEL_LANG    = verilog
MODULE           = test_svo_traversal
SIM              = verilator

include ../Makefile.common
